name : Greeting Message

on : 
  pull_request :
    types : [opened]
    
permissions:
  pull-requests: write
  
jobs:
  build:
    name: Making Greeting
    runs-on: [ubuntu-latest, window-latest]
    steps: 
      - run : gh pr comment $PR_URL --body "Came cho mota bhai"
        env : 
          PR_URL: ${{github.event.pull_request.html_url}}
